version: 2.1
jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: mkdir -p $HOME/.config/jquants && echo "{:mailaddress \"$JQUANTS_USER\" :password \"$JQUANTS_PWD\"}" > $HOME/.config/jquants/login.edn
      - run: clojure -T:build test
      - run: cd examples/JavaSample && ./ci.sh
      - run: cd examples/someml && ./ci.sh
